package com.shatteredpixel.shatteredpixeldungeon.taiga.sprites;

import com.shatteredpixel.shatteredpixeldungeon.taiga.TaigaAssets;

/** Original slate, iron, and snow sprites generated by mod/highland_art.py. */
public class HighlandSprites {
	public static class CrawlerSprite extends TaigaMobSprite { public CrawlerSprite(){ setup(TaigaAssets.HIGHLAND_MOBS,0,3); } }
	public static class SurveyorSprite extends TaigaMobSprite { public SurveyorSprite(){ setup(TaigaAssets.HIGHLAND_MOBS,1,2); } }
	public static class EffigySprite extends TaigaMobSprite { public EffigySprite(){ setup(TaigaAssets.HIGHLAND_MOBS,2,2); } }
	public static class MerchantSprite extends TaigaMobSprite { public MerchantSprite(){ setup(TaigaAssets.HIGHLAND_MOBS,3,2); } }
	public static class LastSurveyorSprite extends TaigaMobSprite { public LastSurveyorSprite(){ setup(TaigaAssets.HIGHLAND_BOSS,0,2,24); } }
}
