package com.shatteredpixel.shatteredpixeldungeon.taiga.sprites;

import com.shatteredpixel.shatteredpixeldungeon.taiga.TaigaAssets;

/** Original sprites generated by mod/orchard_art.py. */
public class OrchardSprites {
	public static class GardenerSprite extends TaigaMobSprite {
		public GardenerSprite(){ setup(TaigaAssets.ORCHARD_MOBS, 0, 2); }
	}
	public static class GlassMothSprite extends TaigaMobSprite {
		public GlassMothSprite(){ setup(TaigaAssets.ORCHARD_MOBS, 1, 3); }
	}
	public static class ScarecrowSprite extends TaigaMobSprite {
		public ScarecrowSprite(){ setup(TaigaAssets.ORCHARD_MOBS, 2, 2); }
	}
	public static class PorterSprite extends TaigaMobSprite {
		public PorterSprite(){ setup(TaigaAssets.ORCHARD_MOBS, 3, 2); }
	}
	public static class ConservatorSprite extends TaigaMobSprite {
		public ConservatorSprite(){ setup(TaigaAssets.ORCHARD_BOSS, 0, 2, 24); }
	}
}
